trigger:
  branches:
    include:
      - main
variables:
  - group: arialmed-variables
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: nodeVersion
    value: '18.x'
  - name: azureServiceConnection
    value: 'arialmed-sc'
    
stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: BuildAndTest
    displayName: 'Build and Test'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: $(nodeVersion)

    - script: npm ci
      displayName: 'Install Dependencies'

    - script: npm run build
      displayName: 'Build Next.js App'
      env:
        NEXT_PUBLIC_FUNCTION_URL: 'https://$(functionAppName).azurewebsites.net'
        NEXT_PUBLIC_STATIC_WEB_APP_URL: $(STATIC_WEB_APP_URL)
        NEXT_PUBLIC_ENDPOINT: $(NEXT_PUBLIC_ENDPOINT)
        PROJECT_ID: $(PROJECT_ID)
        API_KEY: $(API_KEY)
        DATABASE_ID: $(DATABASE_ID)
        PATIENT_COLLECTION_ID: $(PATIENT_COLLECTION_ID)
        DOCTOR_COLLECTION_ID: $(DOCTOR_COLLECTION_ID)
        APPOINTMENT_COLLECTION_ID: $(APPOINTMENT_COLLECTION_ID)
        NEXT_PUBLIC_BUCKET_ID: $(NEXT_PUBLIC_BUCKET_ID)
        NEXT_PUBLIC_ADMIN_PASSKEY: $(NEXT_PUBLIC_ADMIN_PASSKEY)
        NEXT_PUBLIC_SERVICEID: $(NEXT_PUBLIC_SERVICEID)
        NEXT_PUBLIC_TEMPLATEID: $(NEXT_PUBLIC_TEMPLATEID)
        NEXT_PUBLIC_APIKEY: $(NEXT_PUBLIC_APIKEY)

    - script: |
        cp $(System.DefaultWorkingDirectory)/staticwebapp.config.json $(System.DefaultWorkingDirectory)/.next/standalone/
      displayName: 'Copy Static Web App Config'

    - task: ArchiveFiles@2
      displayName: 'Archive Function App'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/app/api'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/function-app.zip'
        replaceExistingArchive: true

    - task: ArchiveFiles@2
      displayName: 'Archive Static Web App'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/.next/standalone'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/static-web-app.zip'
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Build
  jobs:
  - deployment: DeployFunctionApp
    displayName: 'Deploy Function App'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: $(azureServiceConnection)
              appType: 'functionAppLinux'
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/function-app.zip'
              runtimeStack: 'NODE|18'
              appSettings: |
                -NEXT_PUBLIC_ENDPOINT "$(NEXT_PUBLIC_ENDPOINT)"
                -PROJECT_ID "$(PROJECT_ID)"
                -API_KEY "$(API_KEY)"
                -DATABASE_ID "$(DATABASE_ID)"
                -PATIENT_COLLECTION_ID "$(PATIENT_COLLECTION_ID)"
                -DOCTOR_COLLECTION_ID "$(DOCTOR_COLLECTION_ID)"
                -APPOINTMENT_COLLECTION_ID "$(APPOINTMENT_COLLECTION_ID)"
                -NEXT_PUBLIC_BUCKET_ID "$(NEXT_PUBLIC_BUCKET_ID)"
                -NEXT_PUBLIC_ADMIN_PASSKEY "$(NEXT_PUBLIC_ADMIN_PASSKEY)"
                -NEXT_PUBLIC_SERVICEID "$(NEXT_PUBLIC_SERVICEID)"
                -NEXT_PUBLIC_TEMPLATEID "$(NEXT_PUBLIC_TEMPLATEID)"
                -NEXT_PUBLIC_APIKEY "$(NEXT_PUBLIC_APIKEY)"

  - deployment: DeployStaticWebApp
    displayName: 'Deploy Static Web App'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/drop/static-web-app.zip'
              destinationFolder: '$(Pipeline.Workspace)/site'
              cleanDestinationFolder: true
              
          - task: AzureStaticWebApp@0
            inputs:
              app_location: '$(Pipeline.Workspace)/site'
              api_location: ''
              output_location: ''
              azure_static_web_apps_api_token: $(STATIC_WEB_APP_DEPLOYMENT_TOKEN)
              skip_app_build: true
              verbose: true